"""Version information for SC Log Analyzer"""

MAJOR = 0
MINOR = 6
RELEASE = 1
MATURITY = "alpha"  # "alpha", "beta", or "final"
PATCH = "12c8711"

VERSION = f"v{MAJOR}.{MINOR}.{RELEASE}-{PATCH}-{MATURITY}"

def get_version():
    """Return the full version string"""
    return VERSION


# Recent commit messages
COMMIT_MESSAGES = [
    "12c8711: Implement pagination in fetch_record_hashes to retrieve all hash values from Supabase",
    "24a9f37: Refactor get_application_path to simplify path determination logic",
    "ef454d8: Refactor stats message handling to support separate Live and Squadron Battle messages",
    "98ec476: Disable column and row resizing in GridManager to enhance UI stability",
    "03981b1: Update data transfer logic to refine purge behavior based on table naming conventions",
    "4963210: Implement refresh operation tracking and staggered tab refresh logic in DataDisplayManager",
    "0753928: Update .gitignore to include additional VSCode configuration files and memory.json",
    "6d23526: Refactor Supabase data handling to exclude specific fields and simplify key processing",
    "632d5b0: Refactor Supabase table creation to enable default RLS policies and simplify method signature",
    "9c1cbbf: Refactor Supabase configuration checks to simplify validation logic",
    "8d14f00: Add debug utilities for function tracing and logging",
    "8711322: Refactor Supabase integration to extract URL from API key and remove unused config field",
    "37a8ba8: Fix SQL delete statement in purge_table to ensure all records are removed",
    "719f1ad: Fix update_monitoring_buttons call to ensure proper state handling on stop monitoring",
    "6f8391b: Refactor update check and monitoring start delay for improved user experience",
    "7d6ef8d: Refactor monitoring button update logic for improved state handling",
    "2877398: Refactor monitoring button update logic to simplify state management",
    "c6a139e: Implement datasource change handling in ConfigManager and DataDisplayManager",
    "237e39b: Add 'datasource' to preserved keys in ConfigManager configuration renewal",
    "3763e9c: Refactor Supabase data purging to use raw SQL via run_sql RPC, improving efficiency and error handling",
    "4f81e43: Remove Google Sheets to Supabase data migration script",
    "cd54cc4: Add dynamic config application after renewing configuration in ConfigManager",
    "d2ef055: Remove UI checkbox updates for data source settings in DataDisplayManager",
    "f0088b9: Refactor DataTransferDialog to remove Google Sheets and Supabase UI updates, focusing on data source tab updates instead",
    "2c299b7: Enhance add_state_data method to only add keys if they don't already exist in the input data",
    "be5a558: Remove Google Sheets and Supabase options from configuration menu and update related functionality for Discord integration",
    "c3492b7: Merge branch 'feature/supabase-integration'",
    "b21809e: Enhance get_template_path and get_application_path functions to support Nuitka compiled executables",
    "14b965a: Refactor data transfer success criteria and improve warning messaging in DataTransferDialog",
    "4c9e2a6: Enhance data transfer functionality by adding options to purge existing data or skip duplicates, and update UI for better user experience in DataTransferDialog.",
    "f00fb39: Refactor SupabaseManager to remove table caching and enhance table existence check with real-time RPC call",
    "7c1703d: Add purge method to DataProvider and implement in GoogleSheetsDataProvider and SupabaseDataProvider",
    "0d989ad: Refactor StatusBoardBot to replace embed messages with text messages for statistics updates and improve message handling",
    "d7a57b3: Refactor StatusBoardBot to use config manager for configuration values and update data fetching to use a data provider",
    "d827ea8: Enhance DataTransferDialog layout by adjusting size and improving button spacing",
    "5fb7b5a: Refactor Supabase connection handling in ConfigManager to streamline error handling and fallback to Google Sheets",
    "3856c01: Update SupabaseDataProvider to select all fields from the config table",
    "aa5e6b3: Update config.json.template to set datasource to 'googlesheets' and remove use_supabase flag",
    "b3a6d93: Refactor TabCreator to bind refresh button to data manager's method and update GridManager to exclude specific keys from headers",
    "29bc77c: Refactor SupabaseManager to improve table cache TTL and enhance data insertion by converting keys to lowercase for PostgreSQL compatibility",
    "31a36b0: Update sheet list in DataTransfer to include predefined sheets for transfer",
    "e2edad9: Enhance data fetching logic in SupabaseDataProvider to handle resumen_view ordering by total_kills and maintain existing ordering for other tables",
    "2e33d51: Refactor apply_dynamic_config method in ConfigManager to streamline dynamic configuration application and remove unnecessary webhook_url parameter",
    "b67b9ff: Refactor tab creation delay in DataDisplayManager and enhance SupabaseDataProvider query execution",
    "a569d71: Implement data transfer functionality from Google Sheets to Supabase with a dedicated dialog interface",
    "d1ae8ce: Remove saving debug mode in configuration from DataDisplayManager",
    "9fdb754: Add SupabaseDataProvider methods for connection check and batch data processing",
    "d7c73bd: Refactor SupabaseManager connection: allow passing config_manager instance and simplify attribute access in ConfigManager",
    "a1a2ab3: Refactor config_manager usage: streamline attribute access and provide defaults in data provider and log file handler",
    "ee029e6: Enhance LogFileHandler: add EA mode tracking and state reset functionality",
    "14aad4e: Refactor LogFileHandler: replace send_startup_message with direct send_discord_message call",
    "02c8b63: Clean up IDs in LogFileHandler: remove trailing underscores followed by 4+ consecutive digits from data",
    "3ea8d1b: Add Nuitka build script: create build_nuitka.bat for building SCLogAnalyzer with Nuitka",
    "87d6744: Add Nuitka build script: create build_nuitka.bat for building SCLogAnalyzer with Nuitka",
    "211793e: Clean up IDs in LogFileHandler: remove trailing underscores followed by 4+ consecutive digits from data",
    "7a705a2: Add legacy updater support: include LEGACY_UPDATER constant and cleanup logic",
    "cd0e9a4: Refactor .gitignore: add exclusions for VSCode settings and Supabase session SQL file",
    "6b9d19a: Refactor updater module: add legacy updater constant and enhance cleanup logic",
    "996025a: Refactor color mapping: change color key for player_death from \"white,gray\" to \"pink\"",
    "4a7d6a9: Refactor configuration management: unify data source handling across components and update related logic",
    "0e14a6f: Refactor data provider configuration: replace boolean flags with datasource selection and ensure mutual exclusivity in UI components",
    "a4824e1: Refactor ConfigManager: add supabase_url and supabase_key to preserved default keys",
    "9298b6e: Refactor SupabaseManager: enhance _create_table method to support Row Level Security and policies",
    "8b15c75: Refactor MessageBus: implement stdout redirection to message bus and enhance debug mode handling",
    "f522bac: Refactor LogAnalyzerFrame: remove RedirectText class from gui_module and update stdout redirection",
    "4e2d261: Refactor gui_module: remove RedirectText class and enhance regex keys in ConfigDialog",
    "7c1f8a0: Refactor DataProvider: enhance error handling, add retry logic, and improve configuration fetching",
    "9a14597: Refactor DataDisplayManager: enhance debug mode handling and streamline data provider integration",
    "4556b1f: Refactor ConfigManager: integrate message bus for logging and enhance dynamic config handling",
    "5d7fd5d: Refactor LogFileHandler: replace logging with message bus for batch processing and error handling",
    "aa3acf5: Refactor LogAnalyzerFrame: remove Supabase connection handling and update test button for data provider",
    "92d2cc4: Fix launch.json: ensure 'justMyCode' is consistently set to false for all configurations",
    "f9c10ec: Fix LogAnalyzerFrame: streamline configuration dialog handling by directly checking if config was saved",
    "7f96d60: Fix SupabaseManager: enhance error handling and logging during data insertion",
    "2fc853e: Fix LogFileHandler: update batch processing to use current_mode as fallback for sheet name",
    "61b18a3: Fix TabCreator: update submit button binding to use data_manager for form submission",
    "0800318: Refactor SupabaseManager: clean up insert_data method by commenting out unused table creation logic",
    "f5cfa54: Fix SupabaseDataProvider: update data processing loop to correctly unpack data and sheet names",
    "03142c8: Refactor Supabase connection handling: ensure connection attempts are made during initialization and configuration changes",
    "41f9d6a: Enhance SupabaseManager: track connection attempts and improve connection logic",
    "3069345: Refactor DataDisplayManager: update method call to use update_data_queue instead of update_google_sheets",
    "dffb3cb: Fix LogFileHandler: ensure correct sheet name assignment in batch processing",
    "74ce85f: Refactor DataProvider: remove insert_data and send_data methods from base class",
    "2ee75f2: Implement SQL execution and dynamic table creation in SupabaseManager",
    "908c6a7: Refactor DataProvider: centralize logging functionality and update source metadata",
    "a297080: Refactor LogFileHandler: rename 'sheet_name' to 'sheet' in batch processing",
    "d780437: Fix logging messages in LogFileHandler for batch processing",
    "3c01963: Enhance update process: implement retry logic for file replacement and improve error handling",
    "2abf31a: Refactor data processing: unify data queues for Google Sheets and Supabase, and implement batch processing in LogFileHandler",
    "c8da099: Enhance DataDisplayManager and DataProvider with debug mode and logging improvements",
    "e169d32: Add monitoring service, UI components, and window state management",
    "d390f28: Remove setup script: delete setup.py as it is no longer needed",
    "de6f369: Adjust monitoring start delay: set default delay to 1500ms in LogAnalyzerFrame",
    "74607bb: Refactor data handling: implement DataProvider abstraction for Google Sheets and Supabase integration",
    "35e4405: Refactor imports for consistency and clarity: use absolute imports, streamline module imports, and enhance application path handling.",
    "32f5690: Add message bus and Supabase manager for logging and data storage",
    "40a1f31: Implement message bus for centralized logging and event handling across the application",
    "8fbde96: Enhance SupabaseManager: improve table cache refresh logic and allow table creation via data insertion",
    "ef8706b: Fix form submission handling: pass refresh button instead of grid to on_form_submit method",
    "ddfa83e: Update Supabase dependency: change version constraint to > 2.7.0 for integration compatibility",
    "9a6dfa2: Fix form submission handling: pass refresh button instead of grid to on_form_submit method",
    "f2da2cc: Add Supabase integration: implement SupabaseManager for cloud storage and update configuration handling",
]
